development:
  adapter: postgresql
  database: numerology_development
  pool: 5
  host: localhost
  username: postgres
  password: freedom21

test:
  adapter: postgresql
  database: numerology_test
  pool: 5
  host: localhost
  username: postgres
  password: freedom21
